import React, { useEffect, useRef, useState } from 'react';

// Offline, retrieval-style answers from owner-provided portfolio content. No network or model API.
const knowledge = [
  { keys: ['2014 results', '2014 achievements', '2014 tournaments', 'what happened in 2014'], answer: 'The archive records early school and open chess activity in 2014, including the Acharya Shri Sudarshan School Prize Money Chess Tournament. Two newspaper scans dated November 2014 are also in the archive. Browse /gallery/?year=2014 or /tournaments/?year=2014.' },
  { keys: ['2015 results', '2015 achievements', '2015 tournaments', 'what happened in 2015'], answer: 'In 2015, Vivek represented Bihar at the 24th National Youth (Under-25) Chess Championship in Patna. His certificate records 5.5/9 and 20th place. The portfolio also includes his event record under FIDE ID 45046328. Browse /gallery/?year=2015.' },
  { keys: ['2016 results', '2016 achievements', '2016 tournaments', 'what happened in 2016'], answer: 'In 2016, Vivek won the Bihar State Under-15 Championship with 7.5/8. His certificate for the Bihar State U-11/U-17 event records 7/7 and winner. A June 2016 newspaper profile is also in the archive. Browse /gallery/?year=2016.' },
  { keys: ['2017 results', '2017 achievements', '2017 tournaments', 'what happened in 2017'], answer: 'At the 47th National Junior (Under-19) Open Chess Championship in Patna in September 2017, Vivek’s certificate records 6/11 and 39th place. The entry is associated with FIDE ID 45046328. Browse /gallery/?year=2017.' },
  { keys: ['2018 results', '2018 achievements', '2018 tournaments', 'what happened in 2018'], answer: 'The 2018 archive includes Vivek’s first-place ECR Open Rapid Chess Challenge certificate, a first-place Barauni Open certificate recording 7/8, the Bihar State Junior Championship, and 28th place with 7/11 at the National Junior Open. Dated press scans from the year are included too. Browse /gallery/?year=2018.' },
  { keys: ['2019 results', '2019 achievements', '2019 tournaments', 'what happened in 2019'], answer: 'In 2019, Vivek’s Bihar State Under-17 certificate records second place with 6.5/7. The archive also includes Bihar State Rapid coverage dated 21–22 April 2019 and a State Rapid certificate record. Browse /gallery/?year=2019.' },
  { keys: ['2020 results', '2020 achievements', '2020 tournaments', 'what happened in 2020'], answer: 'Vivek’s father, Ravishankar Kumar, passed away on 14 April 2020. Vivek says he stepped back from regular competitive chess to care for his family and manage home, farming and financial responsibilities. The portfolio has no dated certificate or press scan for 2020. Browse /gallery/?year=2020.' },
  { keys: ['2021 results', '2021 achievements', '2021 tournaments', 'what happened in 2021'], answer: 'The current portfolio archive has no dated certificate or press scan for 2021. Vivek describes this broader period as one of family and financial responsibility, with reduced regular tournament activity. Browse /gallery/?year=2021.' },
  { keys: ['2022 results', '2022 achievements', '2022 tournaments', 'what happened in 2022'], answer: 'The 2022 tournament record includes second place at the Bihar State Blitz Championship and fifth place at the MPL National Amateur Below 2000. A Bihar State Senior certificate records 7/9 and fourth place. Browse /gallery/?year=2022.' },
  { keys: ['2023 results', '2023 achievements', '2023 tournaments', 'what happened in 2023'], answer: 'Vivek finished runner-up at the MPL 10th National Amateur Below 2000 (7/9), won the Diksha Bihar State Rapid event and its Blitz section (the certificate records 8/8), placed sixth at the Bihar State Senior, and finished fourth at the International Chess Day Open Blitz. The archive also includes dated Diksha press coverage. Browse /gallery/?year=2023.' },
  { keys: ['2024 results', '2024 achievements', '2024 tournaments', 'what happened in 2024'], answer: 'In 2024, Vivek placed third at the Diamant Cup and Bihar State Amateur Championship, second at the Shivani Cup, and also played the New Delhi Open Rapid and Rajasthan Open Rapid. Tournament records are available at /tournaments/?year=2024; dated certificates or press scans for 2024 are not currently in the image archive.' },
  { keys: ['2025 results', '2025 achievements', '2025 tournaments', 'what happened in 2025'], answer: 'The 2025 record includes sixth place at the Royal Jaipur Open Rapid, 15th at Athens of the East Category B, 16th at the Khelo Chess Academy Open and fifth at the Bihar State Rapid Championship. See /tournaments/?year=2025. Dated certificates or press scans for 2025 are not currently in the image archive.' },
  { keys: ['2026 results', '2026 achievements', '2026 tournaments', 'what happened in 2026'], answer: 'In 2026, Vivek finished runner-up in Category B at the 4th Gujarat International Open with 8.5/10 among 313 players, and placed 10th at the Bihar Open among 615. Browse /gallery/?year=2026 or /tournaments/?year=2026.' },
  { keys: ['who is vivek sharma', 'who is vivek', 'who is he', 'tell me about vivek', 'tell me who vivek is', 'about vivek', 'introduce vivek', 'vivek sharma'], answer: 'Vivek Sharma is an Indian chess player from Gopalpur Village, Naubatpur, in Patna district, Bihar. He was born in 2002 and plays under FIDE ID 45046328. His record includes Bihar state age-group titles, national events, the 2023 Diksha Rapid and Blitz wins, and a runner-up finish at the 2026 Gujarat International Open Category B with 8.5/10. He is working toward his long-term goals of becoming an International Master and Grandmaster and representing India. Ask me about his family, training, story, ratings or any year in his tournament archive.' },
  { keys: ['what does vivek do', 'what does he do', 'profession', 'occupation', 'chess player'], answer: 'Vivek Sharma is an Indian chess player. His FIDE ID is 45046328. He competes in classical, rapid and blitz events and is pursuing his long-term chess ambitions.' },
  { keys: ['known for', 'famous for', 'best achievement', 'biggest achievement'], answer: 'One of Vivek’s major recent results is finishing runner-up in Category B at the 4th Gujarat International Open Grandmasters Chess Tournament 2026, scoring 8.5/10 among 313 players. He also won the Diksha Bihar State Rapid and Blitz sections in 2023 and placed second at the 2023 MPL National Amateur Below 2000.' },
  { keys: ['born', 'birth', 'birthday', 'age', 'when was'], answer: 'Vivek Sharma was born on 16 December 2002 in Gopalpur Village, Naubatpur, Patna district, Bihar, India.' },
  { keys: ['where', 'village', 'gopalpur', 'naubatpur', 'bihar'], answer: 'Vivek is from Gopalpur Village in Naubatpur, Patna district, Bihar, India. His chess journey began far from India’s major chess centres.' },
  { keys: ['father', 'ravishankar', 'first move'], answer: 'Vivek’s father was Ravishankar Kumar. He introduced Vivek and his brother Vishal to chess, became Vivek’s first coach and encouraged his ambitions. He passed away on 14 April 2020. Vivek says he wants to carry his father’s dream forward.' },
  { keys: ['when did his father die', 'when did his father pass', 'father death date', 'date father passed', '14 april 2020', '14-04-2020', 'father died', 'father passed away', 'father passed'], answer: 'Vivek’s father, Ravishankar Kumar, passed away on 14 April 2020.' },
  { keys: ['mother', 'veena'], answer: 'Vivek’s mother is Veena Devi. In his account, she supported the family’s demanding early training routine.' },
  { keys: ['brother', 'vishal'], answer: 'Vivek trained and competed alongside his brother Vishal Sharma, who also became a national-level chess player. They trained together for about five years and won Bihar state age-group titles.' },
  { keys: ['training', 'routine', '3 am', 'sunrise', 'practice'], answer: 'Vivek describes an intense training routine that often began around 3:00 a.m., followed by another long chess-work session from about 8:00 a.m. to 8:00 p.m. Work included openings, tactics, calculation, endgames, preparation and game analysis.' },
  { keys: ['school', 'education', 'aswani'], answer: 'Vivek began at a local rural school and later attended Aswani Public School (CBSE), where he studied through Class 2.' },
  { keys: ['under 13', 'u-13', 'runner up', 'first major', 'fide id'], answer: 'Vivek was runner-up at the Bihar State Under-13 Championship. He later played at the National Under-13 Championship, where his FIDE identity was established. His FIDE ID is 45046328 and his initial FIDE rating was 1510.' },
  { keys: ['2015', 'under 25', 'u-25', 'youth championship'], answer: 'At the 24th National Youth (Under-25) Chess Championship in Patna in October 2015, Vivek represented Bihar. His certificate records 5.5/9 and 20th place. Chess-Results confirms his entry under FIDE ID 45046328. See /tournaments/?year=2015.' },
  { keys: ['2016', 'under 15', 'u-15'], answer: 'In June 2016, Vivek scored 7.5/8 to win the Bihar State Under-15 Championship in Kishanganj.' },
  { keys: ['2017', 'under 19', 'u-19', 'national junior'], answer: 'At the 47th National Junior (Under-19) Open Chess Championship in Patna in September 2017, Vivek’s certificate records 6/11 and 39th place. Chess-Results confirms his event entry under FIDE ID 45046328. See /tournaments/?year=2017.' },
  { keys: ['under 17', 'u-17', 'champion'], answer: 'Vivek says he became Bihar State Under-17 Champion. He describes the period that followed as a difficult dispute that restricted his ability to compete.' },
  { keys: ['ban', 'suspension', 'dispute', 'association', 'federation', 'court', 'high court', 'national selection', 'support rejected'], answer: 'Vivek’s account says a disagreement arose after earlier expected competition reimbursements had not reached him. He says he asked the federation for financial support before a national event, that the request was refused, and that players placed below his state standing were selected instead. His father took the matter to the Patna High Court. A court listing identifies CWJC No. 13363/2019 and the petition challenging a letter that barred him from chess events at national, state and district level: https://patnahighcourt.gov.in/pdf/UPLOADED/5237.PDF. Vivek recalls that the long process was stressful and says he later paused the case after association representatives called him and expressed regret. The selection, support and apology details are Vivek’s personal account, not findings established by the court listing.' },
  { keys: ['2019'], answer: 'In 2019, Vivek was competing in Bihar chess events, including the State Rapid and Under-17 championships. His father passed away the following year, on 14 April 2020.' },
  { keys: ['passed away', 'loss', 'died'], answer: 'Vivek’s father, Ravishankar Kumar, passed away on 14 April 2020. Vivek remembers him as his first chess teacher, guide and strongest believer.' },
  { keys: ['break', 'away', 'hiatus', '2020', 'responsibility', 'family'], answer: 'From 2020, Vivek says he reduced his regular tournament activity for approximately four years while taking care of family, home, farming and financial responsibilities. Databases show selected events in 2022 and 2023, so it was a reduced-activity period rather than a complete absence from tournaments. He says chess’s lessons helped him stay disciplined and rebuild stability.' },
  { keys: ['married', 'wife', 'neha', '2026'], answer: 'Vivek says he married Neha Kumari in 2026, and that this new chapter coincided with his return to chess.' },
  { keys: ['gujarat', 'comeback', 'runner-up', 'runner up', '8.5', 'prize'], answer: 'At the 4th Gujarat International Open Grandmasters Chess Tournament 2026, Category B, Vivek scored 8.5/10 and finished runner-up among 313 players. The supplied details list a ₹1,00,000 prize and trophy. The FIDE tournament report records his FIDE ID, score and a +33 rating change. Event page: /tournaments/gujarat-international-open-2026/ · FIDE report: https://ratings.fide.com/tournament_src_report.phtml?code=476857' },
  { keys: ['achievement', 'achievements', 'tournament result', 'results', 'podium', 'won'], answer: 'Selected records on the portfolio include: runner-up at the 2026 Gujarat International Open Category B (8.5/10 among 313); runner-up at the 2023 MPL National Amateur Below 2000; winner of the 2023 Diksha International Bihar State Rapid Championship and its 8-round Blitz section (8/8 per the uploaded certificate); third at the 2024 Diamant Cup and Bihar State Amateur Championship; and 10th at the 2026 Bihar Open. Explore the tournament archive: /tournaments/ · Gujarat event: /tournaments/gujarat-international-open-2026/' },
  { keys: ['certificate', 'certificates', 'newspaper', 'press', 'news', 'archive by year', 'year archive'], answer: 'The portfolio archive can be browsed by year from 2014 through 2026. Each year page brings together dated certificates, press scans, photographs and tournament records. Scans without a verifiable year are in the “Undated / date unverified” filter. Open /gallery/ or choose a year, for example /gallery/?year=2023.' },
  { keys: ['year archive', 'browse by year', 'records by year'], answer: 'The portfolio archive covers 2014–2026. Choose a year to see dated certificates, press scans and tournament records, or use “Undated / date unverified” for scans whose date is unclear. Open /gallery/.' },
  { keys: ['gold', 'dream', 'goal', 'grandmaster', 'international master', 'represent india'], answer: 'Vivek’s stated goals are to earn the International Master and Grandmaster titles, represent India and one day help bring a gold medal home for the country.' },
  { keys: ['lesson', 'life', 'belief', 'chess teach'], answer: 'Vivek says chess taught him to think before acting, stay disciplined, analyse situations, remain calm under pressure, accept mistakes and keep searching for a solution when things become difficult.' },
  { keys: ['rating', 'classical', 'standard', 'rapid', 'blitz'], answer: 'The portfolio’s October 2026 FIDE snapshot lists Standard (classical) 1975, Rapid 1941 and Blitz 1875. Ratings can change, so the official FIDE profile linked on the site is the best place to check current figures.' },
  { keys: ['title', 'aim', 'arena master'], answer: 'The profile lists Arena International Master (AIM) as Vivek’s FIDE Online Arena title. His FIDE profile does not list an over-the-board title.' },
  { keys: ['links', 'source', 'profile', 'website', 'fide'], answer: 'Official FIDE profile: https://ratings.fide.com/profile/45046328. Tournament, game and archive links are also collected throughout this portfolio.' },
  { keys: ['hello', 'hi', 'hey', 'namaste'], answer: 'Hello! I’m Vivek’s offline portfolio assistant. Ask me about his chess journey, family, training, tournaments, certificates, ratings or goals.' },
];

function answerQuestion(input) {
  const query = input.toLowerCase().replace(/[^a-z0-9\s-]/g, ' ').replace(/\s+/g, ' ').trim();
  const matches = (key) => {
    const escaped = key.toLowerCase().replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\s+/g, '\\s+');
    return new RegExp(`(^|[^a-z0-9])${escaped}($|[^a-z0-9])`).test(query);
  };
  const ranked = knowledge.map((item, index) => ({ item, index, score: item.keys.reduce((score, key) => score + (matches(key) ? Math.max(2, key.split(' ').length * 2) : 0), 0) })).sort((a, b) => b.score - a.score || a.index - b.index);
  return ranked[0]?.score ? ranked[0].item.answer : 'I don’t have that detail in the portfolio information I was given. Try asking about Vivek’s hometown, training, family, chess results, ratings or goals. You can also follow the links on this site to check official chess records.';
}

export default function PortfolioAssistant() {
  const [open, setOpen] = useState(false), [messages, setMessages] = useState([{ from: 'bot', text: 'Hello! Ask me about Vivek’s chess journey, results, ratings or goals. I work offline, with no AI or server API.' }]);
  const [draft, setDraft] = useState(''), [listening, setListening] = useState(false), [voicePending, setVoicePending] = useState(false), [speak, setSpeak] = useState(false);
  const log = useRef(null), recognition = useRef(null), input = useRef(null), voiceTimer = useRef(null);
  useEffect(() => { if (log.current) log.current.scrollTop = log.current.scrollHeight; }, [messages, open]);
  useEffect(() => () => { recognition.current?.stop(); window.clearTimeout(voiceTimer.current); window.speechSynthesis?.cancel(); }, []);
  const submit = (text = draft) => {
    const question = text.trim(); if (!question) return;
    window.clearTimeout(voiceTimer.current); setVoicePending(false);
    const response = answerQuestion(question);
    setMessages(previous => [...previous, { from: 'user', text: question }, { from: 'bot', text: response }]); setDraft('');
    if (speak && 'speechSynthesis' in window) { window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(response); utterance.lang = 'en-IN'; window.speechSynthesis.speak(utterance); }
  };
  const startVoice = () => {
    window.clearTimeout(voiceTimer.current); setVoicePending(false);
    const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!Recognition) { setMessages(previous => [...previous, { from: 'bot', text: 'Voice input is not supported by this browser. You can still type here; spoken replies use your browser’s built-in speech feature.' }]); return; }
    const instance = new Recognition(); recognition.current = instance; instance.lang = 'en-IN'; instance.continuous = false; instance.interimResults = true; instance.maxAlternatives = 1;
    instance.onstart = () => setListening(true);
    instance.onend = () => setListening(false);
    instance.onerror = () => { setListening(false); setVoicePending(false); window.clearTimeout(voiceTimer.current); };
    instance.onresult = event => {
      const transcript = Array.from(event.results).map(result => result[0].transcript).join(' ').trim();
      if (!transcript) return;
      setVoicePending(true);
      window.clearTimeout(voiceTimer.current);
      voiceTimer.current = window.setTimeout(() => submit(transcript), 5000);
    };
    instance.start();
  };
  return <div className="portfolio-assistant">
    {open && <section className="assistant-panel" aria-label="Offline portfolio assistant">
      <header className="assistant-head"><div><span>VIVEK SHARMA</span><small>OFFLINE PORTFOLIO ASSISTANT</small></div><button type="button" onClick={() => setOpen(false)} aria-label="Close chat">×</button></header>
      <div className="assistant-messages" ref={log} aria-live="polite">{messages.map((message, i) => <p className={`assistant-message ${message.from}`} key={i}>{message.text.split(/(https?:\/\/[^\s]+|\/(?:tournaments|games|achievements|gallery)\/(?:[a-z0-9-]+\/)?(?:\?[^\s]+)?)/gi).map((part, j) => /^https?:\/\//i.test(part) || /^\/(?:tournaments|games|achievements|gallery)\//i.test(part) ? <a key={j} href={part} target={/^https?:\/\//i.test(part) ? '_blank' : undefined} rel="noreferrer">{part}</a> : part)}</p>)}</div>
      <div className="assistant-tools"><button type="button" aria-pressed={speak} onClick={() => setSpeak(!speak)}>{speak ? '🔊 READ REPLIES ON' : '🔈 READ REPLIES OFF'}</button><button type="button" onClick={startVoice} aria-pressed={listening||voicePending}>{listening ? 'LISTENING…' : voicePending ? 'ANSWERING IN 5 SEC…' : '🎙 ASK BY VOICE'}</button></div>
      <form className="assistant-form" onSubmit={event => { event.preventDefault(); submit(); }}><input ref={input} value={draft} onChange={event => setDraft(event.target.value)} placeholder="Ask about Vivek…" aria-label="Ask a question"/><button type="submit" aria-label="Send message">↗</button></form>
      <small className="assistant-disclosure">No AI or server API is used. Read-aloud uses your device voice; voice input depends on browser support and its speech-recognition service.</small>
    </section>}
    <button className={`assistant-launch${open ? ' is-open' : ''}`} type="button" onClick={() => { setOpen(!open); if (!open) setTimeout(() => input.current?.focus(), 60); }} aria-expanded={open} aria-label={open ? 'Close portfolio assistant' : 'Ask about Vivek Sharma'}>{open ? '×' : <><span aria-hidden="true">♛</span><span>ASK ABOUT VIVEK</span></>}</button>
  </div>;
}
